// <auto-generated />
namespace HelmesAssignment.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SubmissionSector : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubmissionSector));
        
        string IMigrationMetadata.Id
        {
            get { return "201809221921315_SubmissionSector"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
